# Loops

In [2]:
# Create list of numbers
list_of_values = [1, 2, 3, 4, 5]

print(list_of_values)

[1, 2, 3, 4, 5]


In [5]:
# Cycle through each number and print separately
# loops apply one action to every member of a list
# the "avalue" can be chosen by us, can often just be "i"
# the loop now knows to use "avalue" to mean each value in the list
# if you add the word "break" after print(avalue), it will stop after it runs once

for avalue in list_of_values:
    print(avalue)

1
2
3
4
5


In [6]:
for avalue in list_of_values:
    print("the current value is:", avalue)

the current value is: 1
the current value is: 2
the current value is: 3
the current value is: 4
the current value is: 5


In [7]:
#create new list
num_list = [12, 5, 136, 47]

#for reach item in list, add 10 and print new value
for i in num_list:
    n = i + 10
    print(n)

#without the print, the for loop still runs, the output just doesn't go anywhere
#in our variable list in the terminal below, i will just be whichever the most recent value of i that went through the loop is


22
15
146
57


In [9]:
#how to collect output values in a table or list

#create empty list to store output
new_list = []

#create loop and append (add) output to the list
for i in num_list:
    new_list.append(i + 10)

new_list

# ctrl k c comments a whole chunk of code.
# ctrl k u uncomments it

[22, 15, 146, 57]

# doing a for loop on a data array

In [10]:
import numpy as np

In [14]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# how to pull out one row of the data

data[0]

array([1, 2, 3])

In [17]:
#for just the 1st row of the array, add 10
for i in data[0]:
    n = i + 10
    print(n)

11
12
13


# Functions

In [ ]:
# functions do things once. loops go through all data. functions are often included inside of loops to do one thign to all parts of data
# function structure
# parameter is the inputs into the function
# return means we're done making the function and this is what we want as the output
# variables defined inside the function only exist in the funciton, they wouldn't show up in the terminal below

def func_name(parameter):
    some code here
    return output

In [18]:
#convert mm to in
def mm_to_in(mm):
    inches = mm / 25.4
    return inches

#Test function
#don't have to have the mm = in the argument below, could just put 30

mm_to_in(mm = 30)

1.1811023622047245

In [19]:
# Add docstring to explain what function does
def mm_to_in(mm):
    """Convert input from millimeters to inches.
    
    Parameters
    -----------
    mm : int or float
        numeric value with units in millimeters.
        
    Returns
    -------
    output : int or float
        numeric value with units in inches
    """
    inches = mm / 25.4
    return inches

#show help docstring
help(mm_to_in)

Help on function mm_to_in in module __main__:

mm_to_in(mm)
    Convert input from millimeters to inches.
    
    Parameters
    -----------
    mm : int or float
        numeric value with units in millimeters.
        
    Returns
    -------
    output : int or float
        numeric value with units in inches



In [21]:
#Apply function to a numpy array
data

mm_to_in(mm = data)
#with the above code, the output isn't saved anywhere

array([[0.03937008, 0.07874016, 0.11811024],
       [0.15748031, 0.19685039, 0.23622047],
       [0.27559055, 0.31496063, 0.35433071]])

In [23]:
#to save the output of the function
data_in = mm_to_in(mm = data)

data_in

array([[0.03937008, 0.07874016, 0.11811024],
       [0.15748031, 0.19685039, 0.23622047],
       [0.27559055, 0.31496063, 0.35433071]])

In [24]:
#can we have more than 1 input parameter for function
def multiply_values(x,y):
    z = x * y
    return z

In [26]:
multiply_values(2,3)

-6

In [27]:
def pyramid_volume(basearea, height):
    volume = (1/3) * basearea * height
    return volume

pyramid_volume(10,15)

49.99999999999999

# Combine loops and functions

In [30]:
# first define function
def calculate_square(number):
    """docstring help here"""
    return number ** 2

# the above function is the same as
#def calculate_square(number):
#    n = number ** 2
#    return n

#Create list of numbers as trial dataset
numbers_list = [1, 2, 3, 4, 5]

#Create empty list to collect output
squared_numbers_list = []

for i in numbers_list:
    square_num = calculate_square(i)
    squared_numbers_list.append(square_num)

#squre_num is an intermediate variable, not actually saved and it changes with each loop iteration

squared_numbers_list

[1, 4, 9, 16, 25]